# logging.level.org.springframework.security=DEBUG
logging:
  file:
    name: /tmp/playlist/play-list.log
  level.org.springframework.boot.autoconfigure.jdbc: trace

playlist:
  nameTemplate: Cokolwiek innego niż test

spring:
  datasource:
    url: jdbc:mysql://192.168.238.128:3306/pl
    username: pl
    password: pl
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/change-log.xml
